name: Publish package

on:
  push:
    tags:
      - v*

jobs:
  build-n-publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install wheel twine
      - name: Build Package 📦
        run: |
          python setup.py bdist_wheel sdist
      - name: Publish to PyPi 🚀
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
